"""
Bitcoin Notes URL scraping runner (btc-index Phase 3B).

Reads URL lists generated by bitcoin-notes-prep.py, scrapes each URL
using the shared scraper infrastructure, and writes individual .md files
to btc-index/scraped/ for later corpus ingestion.

Usage:
    python run-bitcoin-notes.py                    # Scrape all categories
    python run-bitcoin-notes.py --category scrapable  # Articles only
    python run-bitcoin-notes.py --category tweet      # Tweets only
    python run-bitcoin-notes.py --dry-run             # Show plan
    python run-bitcoin-notes.py --resume              # Skip already-scraped URLs

Run from btc-index/scraper/:
    ../mcp/.venv/Scripts/python.exe run-bitcoin-notes.py
"""

import argparse
import json
import re
import sys
import time
from datetime import datetime
from pathlib import Path
from urllib.parse import urlparse

import html2text
import httpx

sys.path.insert(0, str(Path(__file__).parent))
from scraper import (
    BROWSER_HEADERS, BROWSER_RETRY_DOMAINS, CLOUDFLARE_DOMAINS,
    MAX_CONTENT_CHARS, PAYWALL_DOMAINS, POLITE_DELAY, SKIP_DOMAINS,
    SKIP_EXTENSIONS, TIMEOUT, USER_AGENT, YOUTUBE_DOMAINS,
    _make_h2t, _strip_noise, _fetch_youtube,
    fetch_url, fetch_url_browser, fetch_tweet, close_browser,
)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

SCRAPER_DIR = Path(__file__).resolve().parent
TBB_ROOT = SCRAPER_DIR.parent.parent
OUTPUT_DIR = TBB_ROOT / "btc-index" / "scraped"
LOG_PATH = SCRAPER_DIR / "bitcoin-notes-wave-log.json"
URLS_JSON = SCRAPER_DIR / "bitcoin-notes-urls.json"


def slugify(url: str) -> str:
    """Create a filesystem-safe slug from a URL."""
    parsed = urlparse(url)
    domain = parsed.netloc.replace(".", "-")
    path = parsed.path.strip("/").replace("/", "--")
    slug = f"{domain}--{path}" if path else domain
    # Remove unsafe chars
    slug = re.sub(r'[^\w\-]', '-', slug)
    # Collapse multiple hyphens
    slug = re.sub(r'-{2,}', '-', slug)
    slug = slug.strip("-")
    # Truncate to reasonable length
    if len(slug) > 120:
        slug = slug[:120].rstrip("-")
    return slug


def write_scraped_file(
    url: str, content: str, status: str, category: str,
    source_files: list[str], error: str = ""
) -> Path:
    """Write a single scraped result to btc-index/scraped/."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    slug = slugify(url)
    filepath = OUTPUT_DIR / f"{slug}.md"

    parsed = urlparse(url)
    domain = parsed.netloc

    header = [
        f"# {domain} -- Scraped Content",
        "",
        f"**URL:** {url}",
        f"**Category:** {category}",
        f"**Scrape status:** {status.upper()}",
        f"**Source notes:** {', '.join(source_files[:3])}",
        f"**Scraped:** {datetime.now().strftime('%Y-%m-%d')}",
    ]
    if error:
        header.append(f"**Error:** {error}")

    header.extend(["", "---", ""])

    if content:
        header.append(content.strip())
    else:
        reason = error or "unknown"
        header.append(f"*No content extracted. Reason: {reason}*")

    filepath.write_text("\n".join(header) + "\n", encoding="utf-8")
    return filepath


# ---------------------------------------------------------------------------
# Scraping dispatchers
# ---------------------------------------------------------------------------

def scrape_article(url: str, client: httpx.Client, h2t) -> tuple[str, str, str]:
    """Scrape an article URL with httpx, falling back to Patchright."""
    parsed = urlparse(url)
    domain = parsed.netloc.lower().removeprefix("www.")

    # Try httpx first
    status, content, error = fetch_url(url, client, h2t)

    # If httpx failed and domain warrants browser retry, try Patchright
    if status == "failed" and (
        domain in BROWSER_RETRY_DOMAINS
        or domain in CLOUDFLARE_DOMAINS
    ):
        status, content, error = fetch_url_browser(url)

    return status, content, error


def scrape_url_list(
    urls: list[dict], category: str, dry_run: bool = False,
    already_done: set = None
) -> list[dict]:
    """Scrape a list of URLs of a given category."""
    if already_done is None:
        already_done = set()

    # Filter out already-scraped
    actionable = [u for u in urls if u["url"] not in already_done]
    skipped_existing = len(urls) - len(actionable)

    if skipped_existing > 0:
        print(f"  Skipping {skipped_existing} already-scraped URLs")

    if not actionable:
        print("  Nothing to scrape.")
        return []

    total = len(actionable)
    est_per_url = 8 if category == "tweet" else 4
    est_minutes = max(1, total * est_per_url // 60)

    print(f"\n  {category.upper()} WAVE: {total} URLs (~{est_minutes} min)")

    if dry_run:
        for u in actionable[:10]:
            print(f"    {u['url'][:80]}")
        if total > 10:
            print(f"    ... and {total - 10} more")
        return []

    results = []
    h2t = _make_h2t()
    start = time.time()

    if category == "tweet":
        # Tweets use Patchright directly
        for i, entry in enumerate(actionable, 1):
            url = entry["url"]
            source_files = entry.get("source_files", [])
            url_display = url[:75] + ("..." if len(url) > 75 else "")
            print(f"  [{i}/{total}] {url_display}", end="", flush=True)

            t0 = time.time()
            status, content, error = fetch_tweet(url)
            elapsed = time.time() - t0

            filepath = write_scraped_file(
                url, content, status, category, source_files, error
            )

            results.append({
                "url": url,
                "status": status,
                "chars": len(content),
                "error": error,
                "file": str(filepath.name),
            })

            tag = {"done": " OK", "partial": " PARTIAL", "failed": " FAIL"
                   }.get(status, " ???")
            chars = f" {len(content):,}ch" if content else ""
            reason = f" -- {error}" if error else ""
            print(f"{tag}{chars}{reason} ({elapsed:.1f}s)")

            if i < total:
                time.sleep(POLITE_DELAY)

    else:
        # Articles use httpx + Patchright fallback
        with httpx.Client(
            headers=BROWSER_HEADERS, follow_redirects=True, timeout=TIMEOUT
        ) as client:
            for i, entry in enumerate(actionable, 1):
                url = entry["url"]
                source_files = entry.get("source_files", [])
                url_display = url[:75] + ("..." if len(url) > 75 else "")
                print(f"  [{i}/{total}] {url_display}", end="", flush=True)

                t0 = time.time()
                status, content, error = scrape_article(url, client, h2t)
                elapsed = time.time() - t0

                filepath = write_scraped_file(
                    url, content, status, category, source_files, error
                )

                results.append({
                    "url": url,
                    "status": status,
                    "chars": len(content),
                    "error": error,
                    "file": str(filepath.name),
                })

                tag = {"done": " OK", "partial": " PARTIAL",
                       "failed": " FAIL", "skipped": " SKIP"
                       }.get(status, " ???")
                chars = f" {len(content):,}ch" if content else ""
                reason = f" -- {error}" if error else ""
                print(f"{tag}{chars}{reason} ({elapsed:.1f}s)")

                if i < total:
                    time.sleep(POLITE_DELAY)

    total_time = time.time() - start
    done = sum(1 for r in results if r["status"] == "done")
    partial = sum(1 for r in results if r["status"] == "partial")
    failed = sum(1 for r in results if r["status"] == "failed")
    total_chars = sum(r["chars"] for r in results)

    print(f"\n  {category.upper()} COMPLETE: {done} done, {partial} partial, "
          f"{failed} failed")
    print(f"  Content: {total_chars:,} chars in {total_time / 60:.1f} min")

    return results


# ---------------------------------------------------------------------------
# Resume support
# ---------------------------------------------------------------------------

def find_already_scraped() -> set[str]:
    """Check which URLs already have scraped files."""
    done = set()
    if not OUTPUT_DIR.exists():
        return done

    for md_file in OUTPUT_DIR.glob("*.md"):
        try:
            text = md_file.read_text(encoding="utf-8", errors="replace")
            # Extract URL from header
            for line in text.splitlines()[:10]:
                if line.startswith("**URL:**"):
                    url = line.replace("**URL:**", "").strip()
                    # Only count as done if status is DONE or PARTIAL
                    if "**Scrape status:** DONE" in text or \
                       "**Scrape status:** PARTIAL" in text:
                        done.add(url)
                    break
        except Exception:
            continue

    return done


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Bitcoin Notes URL scraping runner"
    )
    parser.add_argument(
        "--category", choices=["scrapable", "tweet", "medium", "reddit", "all"],
        default="all", help="Which URL category to scrape",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Show plan without scraping",
    )
    parser.add_argument(
        "--resume", action="store_true",
        help="Skip URLs that already have scraped files",
    )
    parser.add_argument(
        "--limit", type=int, default=0,
        help="Limit number of URLs to scrape (0 = all)",
    )
    args = parser.parse_args()

    # Load URL data
    if not URLS_JSON.exists():
        print("Error: bitcoin-notes-urls.json not found. Run bitcoin-notes-prep.py first.")
        sys.exit(1)

    data = json.loads(URLS_JSON.read_text(encoding="utf-8"))

    # Check resume state
    already_done = set()
    if args.resume:
        already_done = find_already_scraped()
        if already_done:
            print(f"\n  Resume mode: {len(already_done)} URLs already scraped")

    # Determine which categories to run
    categories = []
    if args.category == "all":
        categories = ["scrapable", "tweet", "reddit"]
    else:
        categories = [args.category]

    print(f"\n{'#' * 60}")
    print(f"  BITCOIN NOTES SCRAPING WAVE")
    print(f"  Categories: {', '.join(categories)}")
    print(f"  Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"{'#' * 60}")

    all_results = {}

    for cat in categories:
        key = f"{cat}_urls"
        urls = data.get(key, [])

        if args.limit > 0:
            urls = urls[:args.limit]

        if not urls:
            print(f"\n  No {cat} URLs to process.")
            continue

        try:
            results = scrape_url_list(
                urls, cat, dry_run=args.dry_run, already_done=already_done
            )
            all_results[cat] = results
        except KeyboardInterrupt:
            print(f"\n\n  Interrupted during {cat} wave. Progress saved.")
            break

    # Close browser if used
    close_browser()

    if not args.dry_run and any(all_results.values()):
        # Save log
        log_entry = {
            "wave": "bitcoin-notes",
            "timestamp": datetime.now().isoformat(),
            "categories": {
                cat: {
                    "total": len(results),
                    "done": sum(1 for r in results if r["status"] == "done"),
                    "partial": sum(1 for r in results if r["status"] == "partial"),
                    "failed": sum(1 for r in results if r["status"] == "failed"),
                    "total_chars": sum(r["chars"] for r in results),
                }
                for cat, results in all_results.items()
            },
        }

        if LOG_PATH.exists():
            log = json.loads(LOG_PATH.read_text(encoding="utf-8"))
            if not isinstance(log, list):
                log = [log]
            log.append(log_entry)
        else:
            log = [log_entry]

        LOG_PATH.write_text(
            json.dumps(log, indent=2, default=str), encoding="utf-8"
        )
        print(f"\n  Log saved: {LOG_PATH.name}")

    # Grand total
    total_done = sum(
        sum(1 for r in results if r["status"] == "done")
        for results in all_results.values()
    )
    total_chars = sum(
        sum(r["chars"] for r in results)
        for results in all_results.values()
    )

    print(f"\n{'#' * 60}")
    print(f"  GRAND TOTAL: {total_done} URLs scraped, {total_chars:,} chars")
    print(f"  Output: {OUTPUT_DIR}")
    print(f"{'#' * 60}")


if __name__ == "__main__":
    main()
